name: fl_chart_app
description: FL Chart App is an application to demonstrate samples of the fl_chart (A Flutter package to draw charts).
publish_to: 'none'
version: 1.1.3+10103

environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  universal_platform: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  go_router: ^14.2.7
  dartx: ^1.2.0
  fl_chart:
    path: ../
  flutter_bloc: ^8.1.6
  package_info_plus: ^8.0.2
  equatable: ^2.0.5
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/data/
