name: fl_chart_app
description: FL Chart App is an application to demonstrate samples of the fl_chart (A Flutter package to draw charts).
publish_to: 'none'
version: 1.2.0+10200

environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  universal_platform: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.2
  go_router: ^16.2.4
  dartx: ^1.2.0
  fl_chart:
    path: ../
  flutter_bloc: ^9.1.1
  package_info_plus: ^9.0.0
  equatable: ^2.0.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/data/
