name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.20.0-nullsafety1
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.12.0-259.12.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_drawing: ^0.5.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.3
  pedantic: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter


