name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.50.1
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  mockito: ^5.1.0
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  vector_math: ^2.1.1 #Added to use in some generated codes of mockito
  flutter_test:
    sdk: flutter


