name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.8.5
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_drawing: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
